#!/bin/bash
# set exit mode and save path
set -e
pushd ~/.dotfiles/nixos/

# read arguments to check if we should git push
push='true'
while getopts "o:offline" flag; do
	case "${flag}" in
		o) push='false' ;;
		offline) push='false' ;;
	esac
done

# open file browser and format on exit
ranger
alejandra . &>/dev/null

# get diff. If no diff found, exit.
set +e
git diff --quiet && echo "No changes detected, exiting..." && exit
git diff --quiet **/*.nix
set -e
git diff

if [[ $? == 1 ]]; then
	echo "NixOS Rebuilding..."
	config=./configuration.nix
	sudo nixos-rebuild switch -I nixos-config=$config &> nixos-switch.log || ( cat nixos-switch.log | grep --color error && false)
	gen=$(nixos-rebuild -I nixos-config=$config list-generations | grep current)
	git commit -am "$gen"
else
	git commit -am "Non-config change"
fi
if [[ $push == 'true' ]]; then
	git push
fi
popd
