# configuration.nix
{
  pkgs,
  outputs,
  inputs,
  ...
}: let
  username = "boarder";
in {
  imports = with outputs.modules; [
    inputs.nixos-wsl.nixosModules.default

    profiles-common
    profiles-shell
    system-fonts
    apps-btop
    apps-git
    apps-gpg
    apps-neovim
    apps-nix
    apps-oh-my-posh
    apps-vscode-server
  ];

  my.username = username;
  networking.hostName = "boarding";

  wsl = {
    enable = true;
    wslConf.automount.root = "/mnt";
    wslConf.interop.appendWindowsPath = false;
    wslConf.network.generateHosts = false;
    defaultUser = username;
    startMenuLaunchers = true;

    # docker-desktop.enable = true;
  };

  home-manager.users.${username}.programs.zsh.shellAliases = {
    docker = "/run/current-system/sw/bin/docker";
  };

  users.users."${username}" = {
    isNormalUser = true;
    hashedPassword = "$y$j9T$sD7TNPmhg9Zxso6eUqMV9/$Wa/zdt3yOxWfrY3aLlRjbajyqy/6r6oYInvjplj02O9";
    extraGroups = ["wheel"];
    packages = with pkgs; [
      fastfetch
      ranger
      aria2
      killall
      dig
      ripgrep
      alejandra
      nixd
    ];
  };

  security.pki.certificates = [
    ''
      gitlab
      -----BEGIN CERTIFICATE-----
      MIID8jCCAtqgAwIBAgIQf2rfdCbPbYNBD8XjcvfnYzANBgkqhkiG9w0BAQsFADBs
      MRMwEQYKCZImiZPyLGQBGRYDY29tMR8wHQYKCZImiZPyLGQBGRYPdXh2dGVjaG5v
      bG9naWVzMRQwEgYKCZImiZPyLGQBGRYEY29ycDEeMBwGA1UEAxMVY29ycC1TUlYt
      QURDUy1CUk83LUNBMB4XDTIyMDYyMDEzNDIzNFoXDTI3MDgwMTEyMTIzNlowbDET
      MBEGCgmSJomT8ixkARkWA2NvbTEfMB0GCgmSJomT8ixkARkWD3V4dnRlY2hub2xv
      Z2llczEUMBIGCgmSJomT8ixkARkWBGNvcnAxHjAcBgNVBAMTFWNvcnAtU1JWLUFE
      Q1MtQlJPNy1DQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOvTrmZn
      c86wbTNLkltuaC+LUk669O7DFc+71YSH8z2VKJdNAkd41NRpSJZumvVnArlduTDi
      F9F8v8i1d5fyVEchvZs2RVNHYUZUrCOzCtq52uuzV+sS/cGvJbpXJ4DVrm44hYwS
      j7pVxIUgejmzWDOxehzRyXcq0kf4LfqUXtvm9JBdpCZgSTpjAU9gvzG3ICEj2wiA
      4ODJi7y6oDTmdChhU56oD8/FSoXUc1ZnYnDrFi2fHREDb5ARqVtRFc+jkgTNI0wb
      oQFLa68Wt/bSfylASdevZxRO9r3EU6zwoT+Vcc8Dy2HO42vjXHwz9bRVAGXu9nBT
      gfh4VsNOZqY4tYkCAwEAAaOBjzCBjDATBgkrBgEEAYI3FAIEBh4EAEMAQTAOBgNV
      HQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUsxP1Pj1MoBNN
      4iWFCCRfPWjTY5YwEAYJKwYBBAGCNxUBBAMCAQEwIwYJKwYBBAGCNxUCBBYEFMin
      /RHlpU1Ze1XJGNw1OFuqYYD7MA0GCSqGSIb3DQEBCwUAA4IBAQAzSDTtwzlgz+ht
      cZsusPV18f9JkFIeK/qjJFbn5ELxf03qc25GDYf9Jya5trOsBo1d1Z2tigs0OpfJ
      DzMkRY7Pl+CtRzIawoCZaQ4ymQIH9YZ1nFCKH8eASMSaNMNCxSY55H2tku57boYD
      3vbN1RBKlgUK6yh0mzUhDFHyBL1R6R1HmriQx6DHgvQp5i6tNHNqhJEaC7iOtEcH
      23JMtReA3xVMvpA4TglzpN7cdHhMMpJDENLQtEeb1sRPevur89VPR90NkLcGt9lq
      vifry/puzps43gTfiwZGubhHMh+ODlHbBdMvja+o0FWFjD+aN4VvJuxSUcebdIh2
      5W2mXrND
      -----END CERTIFICATE-----
    ''
    ''
      newunifi
      -----BEGIN CERTIFICATE-----
      MIIFrzCCA5egAwIBAgIQTFiWIIeJd6FO4uAMsU5TzjANBgkqhkiG9w0BAQ0FADBe
      MRMwEQYKCZImiZPyLGQBGRYDY29tMR8wHQYKCZImiZPyLGQBGRYPdXh2dGVjaG5v
      bG9naWVzMRQwEgYKCZImiZPyLGQBGRYEY29ycDEQMA4GA1UEAxMHY2Etcm9vdDAe
      Fw0yNTAxMTUxMTQwMzVaFw0zMDAxMTUxMTUwMzNaMF4xEzARBgoJkiaJk/IsZAEZ
      FgNjb20xHzAdBgoJkiaJk/IsZAEZFg91eHZ0ZWNobm9sb2dpZXMxFDASBgoJkiaJ
      k/IsZAEZFgRjb3JwMRAwDgYDVQQDEwdjYS1yb290MIICIjANBgkqhkiG9w0BAQEF
      AAOCAg8AMIICCgKCAgEAwVaue5dMnRaPIdToSXTRcdCRi0YfRDWJim0SxLrS7yOs
      IXmoTGA3/KFS5AJmABJlUjP86uYwZANIjqkd7RCiYZvMxsQgZedvoWWO13oL3U5H
      60N6NiD8vyPHCPZb7/K4769bA657bemijG75j1VP/PYYSVFkLLUX7koQUMsq9P+Y
      uyPkpI6LrvAZnXcr/erbT0fyI/LkrrRyaH7zROP4SRTXzoUGOFDQnDG55MOP1en9
      VaRfvB8bVMfHJNi3JWMWwSaWLB2fECmbZsAF5+Y5g4s6xa9KX6W+JOplNSKbNgEg
      a0GJ/aWCboiXP4609EFGeBV2NIC/XmxuFHZ51u8ybwf3jjfLGwnENYwxlNo2xnTi
      Ob7z0b17uD1dITMYEof2r8CtBe5eahY5maXphXW3JEMmzazpl8fGwo6Ka1TdW2aP
      y6M63Pmha5puZVGzyAj7u1KUQ0rzIqebQGOzT08Uj9/9I1SFYoMmHNP+o1+FOs58
      8UuodFwUe6CYdaijlP+2r4ZcM00MtuVvwoD7hL3S48mnetOk6Mpyd0wl9J2lcE8q
      8mDOziUFJjkzyxUII1B5vLVlg9Iik0wZCzYPfj9lUwkW9DpFDhQgvTrnJlc8d4cx
      gU6AaMqy8unW916pGvixW/EhhicUwTcMYEeQfCf8V1vTEGWzayJFuzvWntjIxoEC
      AwEAAaNpMGcwEwYJKwYBBAGCNxQCBAYeBABDAEEwDgYDVR0PAQH/BAQDAgGGMA8G
      A1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMXofzuFCdOgSLG/XtayJR3Z0lkZMBAG
      CSsGAQQBgjcVAQQDAgEAMA0GCSqGSIb3DQEBDQUAA4ICAQCXpflC/B7o3SgqwQET
      0B8CPeiKcRZCbeD0NrVErXNxVLZojZstRhr5hE1X3IQ3VbTS6+um/OHNghg5a4V+
      0tdZa76x3YpT+RxIHxGx//F5htVyQ3rM5pzfAA5kkjDah6qFRHv9VsS9bH6bs79O
      6apiUIkIHikBjFcU4uy50lZHsz37CHwDo2nZBIeX4lU/4ZodISQAwnw9/6tVCxEX
      k/hu4Na77wrXKLjml8uE7cswwpQItG7BjmYv7FAZyTxsBWJd7qnYqhfbtk+zzkcO
      gcNW1JVSFTuoJsno15Yuac1EzRl9gq2W0vIwFq2G0Op+jTkhRGWPl4NrVD6fkccT
      EVLa9+HxnE/6yS0osv1Fmm8IbY9MZCDO7JX5w/HWoS5upHHJDjg5SEc7VLRYB4pE
      jiVo7qN/FIswmBgIRwm3gNXI/uf4bdE6xQAHI6M02U2Gv/JSSO0NB1XgLxek21gQ
      2/AxGGA1eV6bZZt3xNTKKJfZNwDJzq+tVQyNE2HkbA4YZp1Fsfv3JVOPGE2HB1N5
      QTCgUS0arjXT7uwCLpvx7dYsa0DdzaRL6IZntaatxt1YYYvqLZvaHp9BBUyA+bGJ
      9POicqYMmf41NVRqijyf3PhlRjiWV5VoWHvgGnBQJTNuIc5p05ACQL9kLPfloEm0
      vuLNOyzAYQ2MGny1Uj/sBwd0Vw==
      -----END CERTIFICATE-----
    ''
    ''
      oldunifi
      -----BEGIN CERTIFICATE-----
      MIIDkDCCAzagAwIBAgIQSlhoa8F4+RwSjvAHRy3vlzAKBggqhkjOPQQDAjA7MQsw
      CQYDVQQGEwJVUzEeMBwGA1UEChMVR29vZ2xlIFRydXN0IFNlcnZpY2VzMQwwCgYD
      VQQDEwNXRTIwHhcNMjQxMDIxMDg0MDU5WhcNMjUwMTEzMDg0MDU4WjATMREwDwYD
      VQQDDAgqLmdjci5pbzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABAQkJjQubDUh
      PZ6nDOMJAnLLCoXtYcRrkVu39eq6TD8wXTq2sz2VnpgzWKU99Qnkq7gkR9Du9Ef9
      9vG7e7LVbMyjggJCMIICPjAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYB
      BQUHAwEwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQURA/qGLTYihiWpCggWId/LPz1
      bUwwHwYDVR0jBBgwFoAUdb7Ed66J9kQ3fc+xaB8dGuvcNFkwWAYIKwYBBQUHAQEE
      TDBKMCEGCCsGAQUFBzABhhVodHRwOi8vby5wa2kuZ29vZy93ZTIwJQYIKwYBBQUH
      MAKGGWh0dHA6Ly9pLnBraS5nb29nL3dlMi5jcnQwGwYDVR0RBBQwEoIIKi5nY3Iu
      aW+CBmdjci5pbzATBgNVHSAEDDAKMAgGBmeBDAECATA2BgNVHR8ELzAtMCugKaAn
      hiVodHRwOi8vYy5wa2kuZ29vZy93ZTIveHV6dDNQVTlGX3cuY3JsMIIBAwYKKwYB
      BAHWeQIEAgSB9ASB8QDvAHUAzPsPaoVxCWX+lZtTzumyfCLphVwNl422qX5UwP5M
      DbAAAAGSrnOKHwAABAMARjBEAiB+VvOb77nttwJXdiKjaqBILODO19dtRbuJgPlp
      TgkPSgIgdVS/E/lbJNktCFyqWN5m/2cr0tNBKOFy9LSjLQZGZacAdgBOdaMnXJoQ
      wzhbbNTfP1LrHfDgjhuNacCx+mSxYpo53wAAAZKuc4nvAAAEAwBHMEUCIQDzlw+E
      y84bpwXXTq8yUldloy5xoPilPAnpmViypmDj8QIgGGBDxllbOU2mKFW1l7NqSFda
      /xdouSG0z6qvLkFvdEowCgYIKoZIzj0EAwIDSAAwRQIgYoMETpg9HQ2CGOQ72Nv+
      nDJBTpaFPPa781brxEzBzjQCIQDGf7RqpfsKK6ufG1qBMZtc0kWVGQDEY9/FLoWv
      goyc3g==
      -----END CERTIFICATE-----
    ''
    ''
      guh
      -----BEGIN CERTIFICATE-----
      MIIDjzCCAzagAwIBAgIQb6Zwj0sVUYcQseNz8Ao8JzAKBggqhkjOPQQDAjA7MQsw
      CQYDVQQGEwJVUzEeMBwGA1UEChMVR29vZ2xlIFRydXN0IFNlcnZpY2VzMQwwCgYD
      VQQDEwNXRTIwHhcNMjUwMTIwMDg0MDEwWhcNMjUwNDE0MDg0MDA5WjATMREwDwYD
      VQQDDAgqLmdjci5pbzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABMZme9GEgX1l
      gWBN+dRxsHR9tHjXAgd9DAfZvO7pb1mLKYflXwpyuy7BOP1P9HTgHSuahPgVI8zI
      jG8wtohcXYyjggJCMIICPjAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYB
      BQUHAwEwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUGfkcaNJDI4uuvPGFGPh5kGDa
      QbswHwYDVR0jBBgwFoAUdb7Ed66J9kQ3fc+xaB8dGuvcNFkwWAYIKwYBBQUHAQEE
      TDBKMCEGCCsGAQUFBzABhhVodHRwOi8vby5wa2kuZ29vZy93ZTIwJQYIKwYBBQUH
      MAKGGWh0dHA6Ly9pLnBraS5nb29nL3dlMi5jcnQwGwYDVR0RBBQwEoIIKi5nY3Iu
      aW+CBmdjci5pbzATBgNVHSAEDDAKMAgGBmeBDAECATA2BgNVHR8ELzAtMCugKaAn
      hiVodHRwOi8vYy5wa2kuZ29vZy93ZTIveHV6dDNQVTlGX3cuY3JsMIIBAwYKKwYB
      BAHWeQIEAgSB9ASB8QDvAHUA5tIxY0B3jMEQQQbXcbnOwdJA9paEhvu6hzId/R43
      jlAAAAGUgxV+vAAABAMARjBEAiBA9Sj4iT6nE5QPFxS4AdLlsRh4KKBOddgV+adf
      faPkRgIgVRzwydPl9bcp+xH+hM71qUcy7cPTdMO5PYeQXaw74LkAdgBOdaMnXJoQ
      wzhbbNTfP1LrHfDgjhuNacCx+mSxYpo53wAAAZSDFX6uAAAEAwBHMEUCIDwDsrLZ
      nxBfphzwk/MZH+ts9FY3pkNurRCdm6CbF4HIAiEApw7+POp76ayh4W3ojHO7WRlT
      4/hTDhhWBWMMrov6tq4wCgYIKoZIzj0EAwIDRwAwRAIgeojW6h3KgPD2XpL1ekyQ
      mN0HO62EtSDuIjXD9Cd0GH4CIBPLdD9NhOVWzk/gUW55q+uLoBY48h2/DIZI1fhL
      qcCa
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIGATCCBOmgAwIBAgITRgAAAOiOb2g3bh/sTgABAAAA6DANBgkqhkiG9w0BAQsF
      ADBsMRMwEQYKCZImiZPyLGQBGRYDY29tMR8wHQYKCZImiZPyLGQBGRYPdXh2dGVj
      aG5vbG9naWVzMRQwEgYKCZImiZPyLGQBGRYEY29ycDEeMBwGA1UEAxMVY29ycC1T
      UlYtQURDUy1CUk83LUNBMB4XDTIzMDcyMDEzMDY0NloXDTI1MDcxOTEzMDY0Nlow
      TTELMAkGA1UEBhMCREsxGTAXBgNVBAoTEFVYViBUZWNobm9sb2dpZXMxIzAhBgNV
      BAMTGmdpdGxhYi51eHZ0ZWNobm9sb2dpZXMuY29tMIIBIjANBgkqhkiG9w0BAQEF
      AAOCAQ8AMIIBCgKCAQEAm+Zwkt1EhJ60ViyYOF/T6xpQFGMT7zgwWUPlmWcSqv8B
      HXLVp6i/GQMDLjKhMcxG+tOFply8r8C1soLwaZz6+fH127idlaoqWBjaL/+lGiNb
      3LJdTXdA2XqK0OuVIJUYL/tlDDQBB0L/O/n7yBtZLeMDc4b+Bw1Lol7Nf3/pCh4r
      6wmduAn9gf8JzEXJKzjzHEKQcLqEjvLKizEtB8s5w/LyC+3B0X0HMJdlQJal1JXz
      cPEvwjtRlT1Fa8jo/G3Kzy3hGAYGix/nPErpx82gTBlEQLQvL5hHvXW2H6Ghz+hk
      zqT53SLpr2nGrjplJNPwNabfcmVDXoEXJ+/KlgBhvwIDAQABo4ICuTCCArUwZQYD
      VR0RBF4wXIIaZ2l0bGFiLnV4dnRlY2hub2xvZ2llcy5jb22CHmNvcnAxLmNvcnAu
      dXh2dGVjaG5vbG9naWVzLmNvbYIeY29ycDIuY29ycC51eHZ0ZWNobm9sb2dpZXMu
      Y29tMB0GA1UdDgQWBBRngb65ZYXJM1PqWX+PsXUfTVT7iTAfBgNVHSMEGDAWgBSz
      E/U+PUygE03iJYUIJF89aNNjljCB6QYDVR0fBIHhMIHeMIHboIHYoIHVhoHSbGRh
      cDovLy9DTj1jb3JwLVNSVi1BRENTLUJSTzctQ0EsQ049U1JWLWFkQ1MtQlJPNyxD
      Tj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049
      Q29uZmlndXJhdGlvbixEQz1jb3JwLERDPXV4dnRlY2hub2xvZ2llcyxEQz1jb20/
      Y2VydGlmaWNhdGVSZXZvY2F0aW9uTGlzdD9iYXNlP29iamVjdENsYXNzPWNSTERp
      c3RyaWJ1dGlvblBvaW50MIHXBggrBgEFBQcBAQSByjCBxzCBxAYIKwYBBQUHMAKG
      gbdsZGFwOi8vL0NOPWNvcnAtU1JWLUFEQ1MtQlJPNy1DQSxDTj1BSUEsQ049UHVi
      bGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlv
      bixEQz1jb3JwLERDPXV4dnRlY2hub2xvZ2llcyxEQz1jb20/Y0FDZXJ0aWZpY2F0
      ZT9iYXNlP29iamVjdENsYXNzPWNlcnRpZmljYXRpb25BdXRob3JpdHkwIQYJKwYB
      BAGCNxQCBBQeEgBXAGUAYgBTAGUAcgB2AGUAcjAOBgNVHQ8BAf8EBAMCBaAwEwYD
      VR0lBAwwCgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggEBAIjzPhiYjBqAUOPa
      FSTllQpHZ7h7a9rZHJbfm0jiHf6LC7alf0TtWCngL25QJLIhp+iGnIyDi+Dv5blD
      QhyhdgeFE12kMEA4auiJQWfJBi0YRj8rkMpDRwhi/qlS4LrBjHTu69v1NWywiWpm
      /A/tK3dN3GrdzGcWdLgSY6mpCHEwzJjWZinSAsf1AH3zPEGVyw8Z9VDd15Euf92y
      4CzgWFeOsUBWPTuTnLpqJIQgPOHEsSvK2fChXSsZb24ubap1lWhpkl8cbV5DNCNh
      Braq8Cm0C971/K1AnvqbwDQ9/ssqqizX1LIxazLSJtiz8PitYz6pkV/liwj2Idcw
      pQa24ao=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDkDCCAzagAwIBAgIQSlhoa8F4+RwSjvAHRy3vlzAKBggqhkjOPQQDAjA7MQsw
      CQYDVQQGEwJVUzEeMBwGA1UEChMVR29vZ2xlIFRydXN0IFNlcnZpY2VzMQwwCgYD
      VQQDEwNXRTIwHhcNMjQxMDIxMDg0MDU5WhcNMjUwMTEzMDg0MDU4WjATMREwDwYD
      VQQDDAgqLmdjci5pbzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABAQkJjQubDUh
      PZ6nDOMJAnLLCoXtYcRrkVu39eq6TD8wXTq2sz2VnpgzWKU99Qnkq7gkR9Du9Ef9
      9vG7e7LVbMyjggJCMIICPjAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYB
      BQUHAwEwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQURA/qGLTYihiWpCggWId/LPz1
      bUwwHwYDVR0jBBgwFoAUdb7Ed66J9kQ3fc+xaB8dGuvcNFkwWAYIKwYBBQUHAQEE
      TDBKMCEGCCsGAQUFBzABhhVodHRwOi8vby5wa2kuZ29vZy93ZTIwJQYIKwYBBQUH
      MAKGGWh0dHA6Ly9pLnBraS5nb29nL3dlMi5jcnQwGwYDVR0RBBQwEoIIKi5nY3Iu
      aW+CBmdjci5pbzATBgNVHSAEDDAKMAgGBmeBDAECATA2BgNVHR8ELzAtMCugKaAn
      hiVodHRwOi8vYy5wa2kuZ29vZy93ZTIveHV6dDNQVTlGX3cuY3JsMIIBAwYKKwYB
      BAHWeQIEAgSB9ASB8QDvAHUAzPsPaoVxCWX+lZtTzumyfCLphVwNl422qX5UwP5M
      DbAAAAGSrnOKHwAABAMARjBEAiB+VvOb77nttwJXdiKjaqBILODO19dtRbuJgPlp
      TgkPSgIgdVS/E/lbJNktCFyqWN5m/2cr0tNBKOFy9LSjLQZGZacAdgBOdaMnXJoQ
      wzhbbNTfP1LrHfDgjhuNacCx+mSxYpo53wAAAZKuc4nvAAAEAwBHMEUCIQDzlw+E
      y84bpwXXTq8yUldloy5xoPilPAnpmViypmDj8QIgGGBDxllbOU2mKFW1l7NqSFda
      /xdouSG0z6qvLkFvdEowCgYIKoZIzj0EAwIDSAAwRQIgYoMETpg9HQ2CGOQ72Nv+
      nDJBTpaFPPa781brxEzBzjQCIQDGf7RqpfsKK6ufG1qBMZtc0kWVGQDEY9/FLoWv
      goyc3g==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFrzCCA5egAwIBAgIQTFiWIIeJd6FO4uAMsU5TzjANBgkqhkiG9w0BAQ0FADBe
      MRMwEQYKCZImiZPyLGQBGRYDY29tMR8wHQYKCZImiZPyLGQBGRYPdXh2dGVjaG5v
      bG9naWVzMRQwEgYKCZImiZPyLGQBGRYEY29ycDEQMA4GA1UEAxMHY2Etcm9vdDAe
      Fw0yNTAxMTUxMTQwMzVaFw0zMDAxMTUxMTUwMzNaMF4xEzARBgoJkiaJk/IsZAEZ
      FgNjb20xHzAdBgoJkiaJk/IsZAEZFg91eHZ0ZWNobm9sb2dpZXMxFDASBgoJkiaJ
      k/IsZAEZFgRjb3JwMRAwDgYDVQQDEwdjYS1yb290MIICIjANBgkqhkiG9w0BAQEF
      AAOCAg8AMIICCgKCAgEAwVaue5dMnRaPIdToSXTRcdCRi0YfRDWJim0SxLrS7yOs
      IXmoTGA3/KFS5AJmABJlUjP86uYwZANIjqkd7RCiYZvMxsQgZedvoWWO13oL3U5H
      60N6NiD8vyPHCPZb7/K4769bA657bemijG75j1VP/PYYSVFkLLUX7koQUMsq9P+Y
      uyPkpI6LrvAZnXcr/erbT0fyI/LkrrRyaH7zROP4SRTXzoUGOFDQnDG55MOP1en9
      VaRfvB8bVMfHJNi3JWMWwSaWLB2fECmbZsAF5+Y5g4s6xa9KX6W+JOplNSKbNgEg
      a0GJ/aWCboiXP4609EFGeBV2NIC/XmxuFHZ51u8ybwf3jjfLGwnENYwxlNo2xnTi
      Ob7z0b17uD1dITMYEof2r8CtBe5eahY5maXphXW3JEMmzazpl8fGwo6Ka1TdW2aP
      y6M63Pmha5puZVGzyAj7u1KUQ0rzIqebQGOzT08Uj9/9I1SFYoMmHNP+o1+FOs58
      8UuodFwUe6CYdaijlP+2r4ZcM00MtuVvwoD7hL3S48mnetOk6Mpyd0wl9J2lcE8q
      8mDOziUFJjkzyxUII1B5vLVlg9Iik0wZCzYPfj9lUwkW9DpFDhQgvTrnJlc8d4cx
      gU6AaMqy8unW916pGvixW/EhhicUwTcMYEeQfCf8V1vTEGWzayJFuzvWntjIxoEC
      AwEAAaNpMGcwEwYJKwYBBAGCNxQCBAYeBABDAEEwDgYDVR0PAQH/BAQDAgGGMA8G
      A1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMXofzuFCdOgSLG/XtayJR3Z0lkZMBAG
      CSsGAQQBgjcVAQQDAgEAMA0GCSqGSIb3DQEBDQUAA4ICAQCXpflC/B7o3SgqwQET
      0B8CPeiKcRZCbeD0NrVErXNxVLZojZstRhr5hE1X3IQ3VbTS6+um/OHNghg5a4V+
      0tdZa76x3YpT+RxIHxGx//F5htVyQ3rM5pzfAA5kkjDah6qFRHv9VsS9bH6bs79O
      6apiUIkIHikBjFcU4uy50lZHsz37CHwDo2nZBIeX4lU/4ZodISQAwnw9/6tVCxEX
      k/hu4Na77wrXKLjml8uE7cswwpQItG7BjmYv7FAZyTxsBWJd7qnYqhfbtk+zzkcO
      gcNW1JVSFTuoJsno15Yuac1EzRl9gq2W0vIwFq2G0Op+jTkhRGWPl4NrVD6fkccT
      EVLa9+HxnE/6yS0osv1Fmm8IbY9MZCDO7JX5w/HWoS5upHHJDjg5SEc7VLRYB4pE
      jiVo7qN/FIswmBgIRwm3gNXI/uf4bdE6xQAHI6M02U2Gv/JSSO0NB1XgLxek21gQ
      2/AxGGA1eV6bZZt3xNTKKJfZNwDJzq+tVQyNE2HkbA4YZp1Fsfv3JVOPGE2HB1N5
      QTCgUS0arjXT7uwCLpvx7dYsa0DdzaRL6IZntaatxt1YYYvqLZvaHp9BBUyA+bGJ
      9POicqYMmf41NVRqijyf3PhlRjiWV5VoWHvgGnBQJTNuIc5p05ACQL9kLPfloEm0
      vuLNOyzAYQ2MGny1Uj/sBwd0Vw==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDtzCCAp+gAwIBAgIIM3DVmn0tkpYwDQYJKoZIhvcNAQELBQAwQjEoMCYGA1UE
      AwwfVW5pRmkgU1NMIENlcnRpZmljYXRlIEF1dGhvcml0eTEWMBQGA1UECgwNVWJp
      cXVpdGkgSW5jLjAeFw0yNDEwMDExNjExMTFaFw0zNDA5MjkxNjExMTFaMEIxKDAm
      BgNVBAMMH1VuaUZpIFNTTCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxFjAUBgNVBAoM
      DVViaXF1aXRpIEluYy4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCW
      O2kjCIq5Tou+6xSkc95DZyHwRTa8rJCsWIJe642GgqBffPhfjv2Fw5NyZB3nlPq1
      opRNOCQbjvWzV2K75E1oLnRVWFKREX52pg9vqhhC0N8c72/D/sykA87rsgDpLEOs
      TacYAaL2L0O9hiEWiFn88x4hlt4qUniRRr3eCGFyPhArjKE/uc/9yie1UCDFicPn
      AlIZyFNm9fc0VBjZsHoKLRP7TZ8mFfDLPz8kuwzQhkHf+dKFJjjjwg4ULRXPjs41
      CcYEpYjLc9cKFlGCC1+UaMLNfaFu7t0INBxo6pzZyVcfR7Yepox3LqoBwAfuPhom
      SceX198MM/zWO/8Do0+HAgMBAAGjgbAwga0wCwYDVR0PBAQDAgEGMAwGA1UdEwQF
      MAMBAf8wcQYDVR0jBGowaIAUuufINwsb8qFch+0VusTuHg2ebiWhRqREMEIxKDAm
      BgNVBAMMH1VuaUZpIFNTTCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxFjAUBgNVBAoM
      DVViaXF1aXRpIEluYy6CCDNw1Zp9LZKWMB0GA1UdDgQWBBS658g3CxvyoVyH7RW6
      xO4eDZ5uJTANBgkqhkiG9w0BAQsFAAOCAQEAOcsGWfxNjZC+lIbFJUTKs4dEkB/e
      KiR0Iz1iiCDNie8867luPYGhSwpOOUQuC8lKa3E7B46tirMWsyftt/DfbNHK5siG
      a6btdWMLhXDsPfLXpKvBHUtFykt7cQNJEesnwjeAzO8t/XOpBiSV3m1C381oG1o+
      +pL619Ep+8t+pebLOVf1cVuDVihtY+JEuZHuMI/soPx8XvNiZto0ntHg7BrWWVJr
      X9+T5lTNJIX8wetN01c6lrOmoPO/hTSaYXo6Odn2Fiw87uetzoYwFIyq5xu7CLO3
      XTiQJAXdXfcTiQUeTqm77xMmrFAkyrquzkRnRPZO8Jz1/Xwarvp4OvY/7Q==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDmDCCAoCgAwIBAgIQet0+LKM57nPOnTaG6Gq4ejANBgkqhkiG9w0BAQsFADBC
      MSgwJgYDVQQDDB9VbmlGaSBTU0wgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRYwFAYD
      VQQKDA1VYmlxdWl0aSBJbmMuMB4XDTI1MDIwOTE1MjExN1oXDTI2MDIxMDE1MjEx
      N1owXjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAk5ZMREwDwYDVQQHEwhOZXcgWW9y
      azEVMBMGA1UEChMMVWJpcXVpdGkgSW5jMRgwFgYDVQQDEw9jYWNoZS5uaXhvcy5v
      cmcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDmZwcxYhlaW7Xo3tHR
      23OpqEOLPQ4drcYb4fMbbVoacEsHoVcWLcOhjOy04v2SaoMFMoKSzAJm0ILeUhEc
      TrRmyzZ3/3mKIbw1sd1l7ag3Kw9cXeRE2lTXEkT9sjp5DatQatshaN4M3VMmsHzv
      lZobhzuTKADwpfXSz7Umqo03q9pMBjsJCJ5nIumfSHoB+iCWPp/vQVsNDIGxPi6T
      m1nnhimIqIuB38k3e8n5Ny6fmY40GymMnLcEEU3zgxAF9jF7rCmUuKBwY3WmB/+s
      UUkWSJZxFc7pyVc+f/5cfJcikQ9+jY0LywKFSMh9T+j8DXUJkr+aaZEYNZgO5/2L
      2+DjAgMBAAGjbjBsMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcD
      AgYIKwYBBQUHAwEwHwYDVR0jBBgwFoAUuufINwsb8qFch+0VusTuHg2ebiUwGgYD
      VR0RBBMwEYIPY2FjaGUubml4b3Mub3JnMA0GCSqGSIb3DQEBCwUAA4IBAQB2/wWV
      e51ycXQXNgwZ9FwXFuAZCwp5vvz/HpCWyLmxSW8lD1kiG57HmnciEoSXwCv/f0r7
      NWVXITp1rSDer0ONmF7eysZQSThQGfNLVI6ElmZ59ZaOu+n8K2kWv1yQwXxg06qD
      QtxD0M9ih3qiV13R/u7kte6A2M7jNwpZMGJXEruHrNIs0LUNgFM9Iki/K9r+kz8n
      n3E0rxcGloyerSKgws5MrfcPngIoxltaFM29pfMVGJf5DK/V5A4sQHCiGGEtHO5D
      mq89C2B5a0ZbFSGPo8P2s+QNCmPI7UMdE73tJz3MDWw7xIzzAAtQ4DARcqgAyVvj
      O8nwxmnp/OlvT4YH
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDtzCCAp+gAwIBAgIIM3DVmn0tkpYwDQYJKoZIhvcNAQELBQAwQjEoMCYGA1UE
      AwwfVW5pRmkgU1NMIENlcnRpZmljYXRlIEF1dGhvcml0eTEWMBQGA1UECgwNVWJp
      cXVpdGkgSW5jLjAeFw0yNDEwMDExNjExMTFaFw0zNDA5MjkxNjExMTFaMEIxKDAm
      BgNVBAMMH1VuaUZpIFNTTCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxFjAUBgNVBAoM
      DVViaXF1aXRpIEluYy4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCW
      O2kjCIq5Tou+6xSkc95DZyHwRTa8rJCsWIJe642GgqBffPhfjv2Fw5NyZB3nlPq1
      opRNOCQbjvWzV2K75E1oLnRVWFKREX52pg9vqhhC0N8c72/D/sykA87rsgDpLEOs
      TacYAaL2L0O9hiEWiFn88x4hlt4qUniRRr3eCGFyPhArjKE/uc/9yie1UCDFicPn
      AlIZyFNm9fc0VBjZsHoKLRP7TZ8mFfDLPz8kuwzQhkHf+dKFJjjjwg4ULRXPjs41
      CcYEpYjLc9cKFlGCC1+UaMLNfaFu7t0INBxo6pzZyVcfR7Yepox3LqoBwAfuPhom
      SceX198MM/zWO/8Do0+HAgMBAAGjgbAwga0wCwYDVR0PBAQDAgEGMAwGA1UdEwQF
      MAMBAf8wcQYDVR0jBGowaIAUuufINwsb8qFch+0VusTuHg2ebiWhRqREMEIxKDAm
      BgNVBAMMH1VuaUZpIFNTTCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxFjAUBgNVBAoM
      DVViaXF1aXRpIEluYy6CCDNw1Zp9LZKWMB0GA1UdDgQWBBS658g3CxvyoVyH7RW6
      xO4eDZ5uJTANBgkqhkiG9w0BAQsFAAOCAQEAOcsGWfxNjZC+lIbFJUTKs4dEkB/e
      KiR0Iz1iiCDNie8867luPYGhSwpOOUQuC8lKa3E7B46tirMWsyftt/DfbNHK5siG
      a6btdWMLhXDsPfLXpKvBHUtFykt7cQNJEesnwjeAzO8t/XOpBiSV3m1C381oG1o+
      +pL619Ep+8t+pebLOVf1cVuDVihtY+JEuZHuMI/soPx8XvNiZto0ntHg7BrWWVJr
      X9+T5lTNJIX8wetN01c6lrOmoPO/hTSaYXo6Odn2Fiw87uetzoYwFIyq5xu7CLO3
      XTiQJAXdXfcTiQUeTqm77xMmrFAkyrquzkRnRPZO8Jz1/Xwarvp4OvY/7Q==
      -----END CERTIFICATE-----
    ''
  ];

  time.timeZone = "Australia/Sydney";
  i18n.defaultLocale = "en_DK.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "da_DK.UTF-8";
    LC_IDENTIFICATION = "da_DK.UTF-8";
    LC_MEASUREMENT = "da_DK.UTF-8";
    LC_MONETARY = "da_DK.UTF-8";
    LC_NAME = "da_DK.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "da_DK.UTF-8";
    LC_TELEPHONE = "da_DK.UTF-8";
    LC_TIME = "da_DK.UTF-8";
  };

  nixpkgs.hostPlatform = "x86_64-linux";
  system.stateVersion = "24.05";
}
